# Generated by Django 6.0.5 on 2026-08-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
