# Generated by Django 6.0.5 on 2026-09-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
