# Generated by Django 6.0.5 on 2026-08-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='conversationmessage',
            name='content',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
