# Generated by Django 6.0.5 on 2026-05-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default.png', null=True, upload_to='item_images'),
        ),
    ]
