# Generated by Django 6.0.5 on 2026-08-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='itemimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='item_videos/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/'),
        ),
    ]
