# Generated by Django 6.0.5 on 2026-08-14 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_itemimage_media_type_itemimage_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='item_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm'])]),
        ),
    ]
