# Generated by Django 6.0.5 on 2026-08-21 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_category_options_category_banner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('color_code', models.CharField(blank=True, max_length=10, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, help_text='Extra price on top of base price', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='item.item')),
            ],
            options={
                'ordering': ('size', 'color'),
            },
        ),
    ]
