# Generated by Django 6.0.5 on 2026-08-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
