# Generated by Django 6.0.5 on 2026-09-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
