# Generated by Django 6.0.5 on 2026-08-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_stock_deducted_order_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_confirmed', 'Payment Confirmed'), ('confirmed', 'Order Confirmed (COD)'), ('processing', 'Processing'), ('picked_up', 'Picked Up by Courier'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('returned', 'Returned')], db_index=True, default='pending_payment', max_length=20),
        ),
    ]
